### ISSUE TITLE
Compass error

### ISSUE THREAD

**Issue by juergen-pecher** [mydropteam/drupal-php_images#3]
error message

```
Running "compass:dist" (compass) task
Warning: Command failed: compass --version
/var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/urls.rb:5:in `has?': undefined method `has?' for Sass::Util:Module (NoMethodError)
    from /var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/urls.rb:9:in `included'
    from /var/lib/gems/2.1.0/gems/sass-3.5.0.pre.rc.1/lib/sass/script/functions.rb:632:in `include'
    from /var/lib/gems/2.1.0/gems/sass-3.5.0.pre.rc.1/lib/sass/script/functions.rb:632:in `include'
    from /var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions.rb:23:in `<module:Functions>'
    from /var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions.rb:19:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions.rb:9:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/compass-core-1.0.3/lib/compass/core.rb:68:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/lib/compass.rb:14:in `block in <top (required)>'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/lib/compass.rb:13:in `each'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/lib/compass.rb:13:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/bin/compass:20:in `block in <top (required)>'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/bin/compass:8:in `fallback_load_path'
    from /var/lib/gems/2.1.0/gems/compass-1.0.3/bin/compass:19:in `<top (required)>'
    from /usr/local/bin/compass:23:in `load'
    from /usr/local/bin/compass:23:in `<main>'
 Use --force to continue.
```

Seems that we need to explicitly install sass ...

**Comment by html-koder-com** [comment]
The same error for me. I run the Docker:

```
FROM node:latest

# install ruby and compass
RUN apt-get update -y && apt-get -y -q install \
    gcc make ruby ruby-dev libxml2 libxml2-dev libxslt1-dev git bzip2 && gem install compass

...other commands...
```

**Comment by html-koder-com** [comment]
I managed to solve it this way:

```
RUN apt-get update -y && apt-get -y -q install \
    gcc make ruby ruby-dev libxml2 libxml2-dev libxslt1-dev git bzip2 && gem install sass compass
```

(see the new "sass" after gem install)

**Comment by juergen-pecher** [comment]
debugging validated
